import { Card, CardContent } from "@/components/ui/card"
import { FileText, Brain, BookOpen, GraduationCap, Calendar, BarChart3 } from "lucide-react"

const features = [
  {
    icon: FileText,
    title: "AI Short Notes",
    description: "Concise, AI-generated notes tailored to your syllabus",
    gradient: "from-purple-500 to-purple-600",
    bgGradient: "from-purple-50 to-purple-100",
  },
  {
    icon: Brain,
    title: "Adaptive Quizzes",
    description: "Quizzes that adapt to your learning pace and knowledge gaps",
    gradient: "from-blue-500 to-blue-600",
    bgGradient: "from-blue-50 to-blue-100",
  },
  {
    icon: BookOpen,
    title: "Past Papers (15 Years)",
    description: "Access 15 years of past papers with detailed solutions",
    gradient: "from-purple-500 to-blue-500",
    bgGradient: "from-purple-50 to-blue-50",
  },
  {
    icon: GraduationCap,
    title: "AI Mock Exams",
    description: "Realistic mock exams generated by AI based on exam patterns",
    gradient: "from-blue-500 to-cyan-500",
    bgGradient: "from-blue-50 to-cyan-50",
  },
  {
    icon: Calendar,
    title: "Smart Study Planner",
    description: "AI-powered study plans customized to your exam schedule",
    gradient: "from-purple-600 to-purple-500",
    bgGradient: "from-purple-50 to-purple-100",
  },
  {
    icon: BarChart3,
    title: "Progress Analytics",
    description: "Track your progress with detailed performance insights",
    gradient: "from-blue-600 to-purple-500",
    bgGradient: "from-blue-50 to-purple-50",
  },
]

export function FeaturesSection() {
  return (
    <section id="features" className="py-24 bg-white relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-100 text-purple-700 text-sm font-medium mb-4">
            Features
          </div>
          <h2 className="text-4xl sm:text-5xl font-bold mb-4 text-gray-900 text-balance">
            Everything You Need to Excel
          </h2>
          <p className="text-gray-600 max-w-2xl mx-auto text-lg">
            Comprehensive tools designed specifically for A/L Science students in Sri Lanka
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <Card
              key={index}
              className="group bg-white border border-gray-200 rounded-2xl hover:shadow-xl hover:shadow-purple-500/10 hover:border-purple-200 transition-all duration-300"
            >
              <CardContent className="p-6">
                <div
                  className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${feature.bgGradient} flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300`}
                >
                  <feature.icon
                    className={`w-7 h-7 bg-gradient-to-r ${feature.gradient} bg-clip-text`}
                    style={{ color: feature.gradient.includes("purple") ? "#8b5cf6" : "#3b82f6" }}
                  />
                </div>
                <h3 className="text-xl font-semibold mb-2 text-gray-900">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  )
}
